const specialists = {
    Islamabad: [
      "Best Dentist in Islamabad",
      "Best Family Physician in Islamabad",
      "Best Obstetrician in Islamabad",
      "Best Consultant Physician in Islamabad",
      "Best Psychologist in Islamabad",
      "Best Pediatrician in Islamabad",
      "Best Laparoscopic Surgeon in Islamabad",
      "Best Orthopedic Surgeon in Islamabad",
      "Best Cardiologist in Islamabad",
      "Best Nutritionist in Islamabad",
      "Best Neonatologist in Islamabad",
      "Best Dietitian in Islamabad",
      "Best Internal Medicine Specialist in Islamabad",
      "Best Gynecologist in Islamabad",
      "Best General Physician in Islamabad",
      "Best General Surgeon in Islamabad",
      "Best Dermatologist in Islamabad",
      "Best Cosmetologist in Islamabad",
      "Best Physiotherapist in Islamabad",
      "Best Diabetologist in Islamabad",
      "Best Gastroenterologist in Islamabad",
      "Best ENT Specialist in Islamabad",
      "Best Urologist in Islamabad",
      "Best ENT Surgeon in Islamabad",
    ],
    Rawalpindi: [
      "Best Dentist in Rawalpindi",
      "Best Family Physician in Rawalpindi",
      "Best Obstetrician in Rawalpindi",
      "Best Consultant Physician in Rawalpindi",
      "Best Psychologist in Rawalpindi",
      "Best Pediatrician in Rawalpindi",
      "Best Laparoscopic Surgeon in Rawalpindi",
      "Best Orthopedic Surgeon in Rawalpindi",
      "Best Cardiologist in Rawalpindi",
      "Best Nutritionist in Rawalpindi",
      "Best Neonatologist in Rawalpindi",
      "Best Dietitian in Rawalpindi",
      "Best Internal Medicine Specialist in Rawalpindi",
      "Best Gynecologist in Rawalpindi",
      "Best General Physician in Rawalpindi",
      "Best General Surgeon in Rawalpindi",
      "Best Dermatologist in Rawalpindi",
      "Best Cosmetologist in Rawalpindi",
      "Best Physiotherapist in Rawalpindi",
      "Best Diabetologist in Rawalpindi",
      "Best Gastroenterologist in Rawalpindi",
      "Best ENT Specialist in Rawalpindi",
      "Best Urologist in Rawalpindi",
      "Best ENT Surgeon in Rawalpindi",
    ],
  };
  
  export default specialists;
  